// @generated by scripts/project-linear-capability-bodies.mjs
// Source: capabilities/builds-workspace-registry/3-semantic-execution-models/builds-workspace-registry.execution.sej.v1.json
import type { BuildsWorkspaceRegistryContext } from "../types/builds-workspace-registry-context.type.js";

export async function buildsWorkspaceRegistry(
  context: BuildsWorkspaceRegistryContext,
): Promise<unknown> {
  const authority = await context.edges.invokes("resolves-builds-workspace-registry-authority", context);
  const execution = await context.edges.invokes("executes-resolved-builds-workspace-registry", authority);
  return context.edges.projects("projects-builds-workspace-registry-receipt", execution);
}
