// @generated by scripts/project-linear-capability-bodies.mjs

export const projectsCapabilityTypes = Object.freeze({
  capabilityId: "discovers-workspace-json-documents",
  contextContract: "discovers-workspace-json-documents.input.v1",
  resultContract: "discovers-workspace-json-documents.receipt.v1",
  status: "drafted",
});
