// @generated by scripts/project-linear-capability-bodies.mjs

export const projectsCapabilityBody = Object.freeze({
  capabilityId: "discovers-workspace-json-documents",
  executionModelId: "executes-discovers-workspace-json-documents",
  bodyIdentity: "discovers-workspace-json-documents",
  source: "capabilities/discovers-workspace-json-documents/3-semantic-execution-models/discovers-workspace-json-documents.execution.sej.v1.json",
  status: "drafted",
});
