// @generated by scripts/project-linear-capability-bodies.mjs

export const registersProjectsWorkspaceRegistrySnapshotAuthority = Object.freeze({
  capabilityId: "projects-workspace-registry-snapshot",
  authorityRoot: "capabilities/projects-workspace-registry-snapshot",
  status: "drafted",
  executionModelId: "executes-projects-workspace-registry-snapshot",
  implementationDisposition: "semantic-authority-not-yet-implemented",
});
