// @generated by scripts/project-json-schema-types.mjs
// Sources: capabilities/executes-relational-query/contracts/relational-query-plan.schema.v1.json, capabilities/executes-relational-query/contracts/authorized-relational-query-execution.schema.v1.json, capabilities/executes-relational-query/contracts/relational-query-result.schema.v1.json
import type { JsonObject, JsonValue } from "@deterministic-solutions/semantic-kernel";

export type RelationalSource = Readonly<{
  readonly sourceId: string;
  readonly alias: string;
}>;

export type RelationalJoin = Readonly<{
  readonly kind: "inner" | "left" | "right" | "full" | "cross";
  readonly source: RelationalSource;
  readonly on?: RelationalExpression;
}>;

export type RelationalSelection = Readonly<{
  readonly expression: RelationalExpression;
  readonly alias?: string;
}>;

export type RelationalOrder = Readonly<{
  readonly expression: RelationalExpression;
  readonly direction: "ascending" | "descending";
}>;

export type RelationalExpression =
  | Readonly<{
    readonly kind: "literal";
    readonly value: JsonValue;
  }>
  | Readonly<{
    readonly kind: "reference";
    readonly path: readonly string[];
  }>
  | Readonly<{
    readonly kind: "wildcard";
    readonly qualifier?: string;
  }>
  | Readonly<{
    readonly kind: "unary";
    readonly operator: "not" | "negate" | "is-null" | "is-not-null";
    readonly operand: RelationalExpression;
  }>
  | Readonly<{
    readonly kind: "binary";
    readonly operator: "or" | "and" | "equals" | "not-equals" | "greater-than" | "greater-than-or-equal" | "less-than" | "less-than-or-equal" | "add" | "subtract" | "multiply" | "divide" | "modulo" | "like" | "in";
    readonly left: RelationalExpression;
    readonly right: RelationalExpression;
  }>
  | Readonly<{
    readonly kind: "call";
    readonly function: "count" | "sum" | "average" | "minimum" | "maximum" | "lower" | "upper" | "length" | "coalesce";
    readonly arguments: readonly RelationalExpression[];
    readonly distinct?: boolean;
  }>
  | Readonly<{
    readonly kind: "list";
    readonly items: readonly RelationalExpression[];
  }>;

export type RelationalQueryPlan = Readonly<{
  readonly planType: "relational-query-plan.v1";
  readonly ctes: Readonly<Record<string, RelationalQueryPlan>>;
  readonly from?: RelationalSource;
  readonly joins: readonly RelationalJoin[];
  readonly where?: RelationalExpression;
  readonly groupBy: readonly RelationalExpression[];
  readonly having?: RelationalExpression;
  readonly selections: readonly RelationalSelection[];
  readonly distinct: boolean;
  readonly orderBy: readonly RelationalOrder[];
  readonly offset: number;
  readonly limit?: number;
}>;

export type RelationalSources = Readonly<Record<string, readonly JsonObject[]>>;

export type AuthorizedRelationalQueryExecution = Readonly<{
  readonly plan: RelationalQueryPlan;
  readonly sources: Readonly<Record<string, readonly JsonObject[]>>;
}>;

export type RelationalQueryResult = Readonly<{
  readonly columns: readonly string[];
  readonly rows: readonly JsonObject[];
  readonly rowCount: number;
}>;
