// @generated by scripts/project-linear-capability-bodies.mjs
// Source: capabilities/summarizes-workspace-registry/3-semantic-execution-models/summarizes-workspace-registry.execution.sej.v1.json
import type { SummarizesWorkspaceRegistryContext } from "../types/summarizes-workspace-registry-context.type.js";

export async function summarizesWorkspaceRegistry(
  context: SummarizesWorkspaceRegistryContext,
): Promise<unknown> {
  const authority = await context.edges.invokes("resolves-summarizes-workspace-registry-authority", context);
  const execution = await context.edges.invokes("executes-resolved-summarizes-workspace-registry", authority);
  return context.edges.projects("projects-summarizes-workspace-registry-receipt", execution);
}
