// @generated by scripts/project-linear-capability-bodies.mjs

export const projectsCapabilityBody = Object.freeze({
  capabilityId: "persists-workspace-registry-snapshot",
  executionModelId: "executes-persists-workspace-registry-snapshot",
  bodyIdentity: "persists-workspace-registry-snapshot",
  source: "capabilities/persists-workspace-registry-snapshot/3-semantic-execution-models/persists-workspace-registry-snapshot.execution.sej.v1.json",
  status: "drafted",
});
