// @generated by scripts/project-linear-capability-bodies.mjs

export const registersRecordsWorkspaceRegistryProvenanceAuthority = Object.freeze({
  capabilityId: "records-workspace-registry-provenance",
  authorityRoot: "capabilities/records-workspace-registry-provenance",
  status: "drafted",
  executionModelId: "executes-records-workspace-registry-provenance",
  implementationDisposition: "semantic-authority-not-yet-implemented",
});
