// @generated by scripts/project-linear-capability-bodies.mjs

export const projectsCapabilityTypes = Object.freeze({
  capabilityId: "records-workspace-registry-provenance",
  contextContract: "records-workspace-registry-provenance.input.v1",
  resultContract: "records-workspace-registry-provenance.receipt.v1",
  status: "drafted",
});
