// @generated by scripts/project-linear-capability-bodies.mjs

export const projectsCapabilityBody = Object.freeze({
  capabilityId: "records-workspace-registry-provenance",
  executionModelId: "executes-records-workspace-registry-provenance",
  bodyIdentity: "records-workspace-registry-provenance",
  source: "capabilities/records-workspace-registry-provenance/3-semantic-execution-models/records-workspace-registry-provenance.execution.sej.v1.json",
  status: "drafted",
});
