// @generated by scripts/project-linear-capability-bodies.mjs
// Source: capabilities/resolves-workspace-document-references/3-semantic-execution-models/resolves-workspace-document-references.execution.sej.v1.json
import type { ResolvesWorkspaceDocumentReferencesContext } from "../types/resolves-workspace-document-references-context.type.js";

export async function resolvesWorkspaceDocumentReferences(
  context: ResolvesWorkspaceDocumentReferencesContext,
): Promise<unknown> {
  const authority = await context.edges.invokes("resolves-resolves-workspace-document-references-authority", context);
  const execution = await context.edges.invokes("executes-resolved-resolves-workspace-document-references", authority);
  return context.edges.projects("projects-resolves-workspace-document-references-receipt", execution);
}
