// @generated by scripts/project-linear-capability-bodies.mjs
// Source: capabilities/records-workspace-registry-provenance/3-semantic-execution-models/records-workspace-registry-provenance.execution.sej.v1.json
import type { RecordsWorkspaceRegistryProvenanceContext } from "../types/records-workspace-registry-provenance-context.type.js";

export async function recordsWorkspaceRegistryProvenance(
  context: RecordsWorkspaceRegistryProvenanceContext,
): Promise<unknown> {
  const authority = await context.edges.invokes("resolves-records-workspace-registry-provenance-authority", context);
  const execution = await context.edges.invokes("executes-resolved-records-workspace-registry-provenance", authority);
  return context.edges.projects("projects-records-workspace-registry-provenance-receipt", execution);
}
