// @generated by scripts/project-linear-capability-bodies.mjs

export const registersDiscoversWorkspaceJsonDocumentsAuthority = Object.freeze({
  capabilityId: "discovers-workspace-json-documents",
  authorityRoot: "capabilities/discovers-workspace-json-documents",
  status: "drafted",
  executionModelId: "executes-discovers-workspace-json-documents",
  implementationDisposition: "semantic-authority-not-yet-implemented",
});
