// @generated by scripts/project-linear-capability-bodies.mjs

export const projectsCapabilityBody = Object.freeze({
  capabilityId: "observes-workspace-json-document",
  executionModelId: "executes-observes-workspace-json-document",
  bodyIdentity: "observes-workspace-json-document",
  source: "capabilities/observes-workspace-json-document/3-semantic-execution-models/observes-workspace-json-document.execution.sej.v1.json",
  status: "drafted",
});
