// @generated by scripts/project-linear-capability-bodies.mjs

export const registersBuildsWorkspaceRegistryAuthority = Object.freeze({
  capabilityId: "builds-workspace-registry",
  authorityRoot: "capabilities/builds-workspace-registry",
  status: "drafted",
  executionModelId: "executes-builds-workspace-registry",
  implementationDisposition: "semantic-authority-not-yet-implemented",
});
