// @generated by scripts/project-linear-capability-bodies.mjs
// Source: capabilities/discovers-workspace-json-documents/3-semantic-execution-models/discovers-workspace-json-documents.execution.sej.v1.json
import type { DiscoversWorkspaceJsonDocumentsContext } from "../types/discovers-workspace-json-documents-context.type.js";

export async function discoversWorkspaceJsonDocuments(
  context: DiscoversWorkspaceJsonDocumentsContext,
): Promise<unknown> {
  const authority = await context.edges.invokes("resolves-discovers-workspace-json-documents-authority", context);
  const execution = await context.edges.invokes("executes-resolved-discovers-workspace-json-documents", authority);
  return context.edges.projects("projects-discovers-workspace-json-documents-receipt", execution);
}
