// @generated by scripts/project-linear-capability-bodies.mjs
// Source: capabilities/classifies-workspace-json-document/3-semantic-execution-models/classifies-workspace-json-document.execution.sej.v1.json
import type { ClassifiesWorkspaceJsonDocumentContext } from "../types/classifies-workspace-json-document-context.type.js";

export async function classifiesWorkspaceJsonDocument(
  context: ClassifiesWorkspaceJsonDocumentContext,
): Promise<unknown> {
  const authority = await context.edges.invokes("resolves-classifies-workspace-json-document-authority", context);
  const execution = await context.edges.invokes("executes-resolved-classifies-workspace-json-document", authority);
  return context.edges.projects("projects-classifies-workspace-json-document-receipt", execution);
}
