// @generated by scripts/project-linear-capability-bodies.mjs
// Source: capabilities/projects-workspace-registry-snapshot/3-semantic-execution-models/projects-workspace-registry-snapshot.execution.sej.v1.json
import type { ProjectsWorkspaceRegistrySnapshotContext } from "../types/projects-workspace-registry-snapshot-context.type.js";

export async function projectsWorkspaceRegistrySnapshot(
  context: ProjectsWorkspaceRegistrySnapshotContext,
): Promise<unknown> {
  const authority = await context.edges.invokes("resolves-projects-workspace-registry-snapshot-authority", context);
  const execution = await context.edges.invokes("executes-resolved-projects-workspace-registry-snapshot", authority);
  return context.edges.projects("projects-projects-workspace-registry-snapshot-receipt", execution);
}
