// @generated by scripts/project-linear-capability-bodies.mjs

export const registersObservesWorkspaceJsonDocumentAuthority = Object.freeze({
  capabilityId: "observes-workspace-json-document",
  authorityRoot: "capabilities/observes-workspace-json-document",
  status: "drafted",
  executionModelId: "executes-observes-workspace-json-document",
  implementationDisposition: "semantic-authority-not-yet-implemented",
});
