// @generated by scripts/project-linear-capability-bodies.mjs
import type { SemanticEdges } from "@deterministic-solutions/semantic-kernel";

export type ProjectsWorkspaceRegistrySnapshotContext = Readonly<{
  edges: SemanticEdges;
  request: unknown;
}>;
