// @generated by scripts/project-linear-capability-bodies.mjs

export const registersResolvesWorkspaceDocumentReferencesAuthority = Object.freeze({
  capabilityId: "resolves-workspace-document-references",
  authorityRoot: "capabilities/resolves-workspace-document-references",
  status: "drafted",
  executionModelId: "executes-resolves-workspace-document-references",
  implementationDisposition: "semantic-authority-not-yet-implemented",
});
