// @generated by scripts/project-linear-capability-bodies.mjs

export const registersSummarizesWorkspaceRegistryAuthority = Object.freeze({
  capabilityId: "summarizes-workspace-registry",
  authorityRoot: "capabilities/summarizes-workspace-registry",
  status: "drafted",
  executionModelId: "executes-summarizes-workspace-registry",
  implementationDisposition: "semantic-authority-not-yet-implemented",
});
