// @generated by scripts/project-linear-capability-bodies.mjs

export const projectsCapabilityBody = Object.freeze({
  capabilityId: "resolves-workspace-registry-request",
  executionModelId: "executes-resolves-workspace-registry-request",
  bodyIdentity: "resolves-workspace-registry-request",
  source: "capabilities/resolves-workspace-registry-request/3-semantic-execution-models/resolves-workspace-registry-request.execution.sej.v1.json",
  status: "drafted",
});
