// @generated by scripts/project-linear-capability-bodies.mjs

export const projectsCapabilityTypes = Object.freeze({
  capabilityId: "resolves-workspace-registry-request",
  contextContract: "resolves-workspace-registry-request.input.v1",
  resultContract: "resolves-workspace-registry-request.receipt.v1",
  status: "drafted",
});
