// @generated by scripts/project-linear-capability-bodies.mjs
// Source: capabilities/persists-workspace-registry-snapshot/3-semantic-execution-models/persists-workspace-registry-snapshot.execution.sej.v1.json
import type { PersistsWorkspaceRegistrySnapshotContext } from "../types/persists-workspace-registry-snapshot-context.type.js";

export async function persistsWorkspaceRegistrySnapshot(
  context: PersistsWorkspaceRegistrySnapshotContext,
): Promise<unknown> {
  const authority = await context.edges.invokes("resolves-persists-workspace-registry-snapshot-authority", context);
  const execution = await context.edges.invokes("executes-resolved-persists-workspace-registry-snapshot", authority);
  return context.edges.projects("projects-persists-workspace-registry-snapshot-receipt", execution);
}
