// @generated by scripts/project-linear-capability-bodies.mjs
// Source: capabilities/resolves-workspace-registry-request/3-semantic-execution-models/resolves-workspace-registry-request.execution.sej.v1.json
import type { ResolvesWorkspaceRegistryRequestContext } from "../types/resolves-workspace-registry-request-context.type.js";

export async function resolvesWorkspaceRegistryRequest(
  context: ResolvesWorkspaceRegistryRequestContext,
): Promise<unknown> {
  const authority = await context.edges.invokes("resolves-resolves-workspace-registry-request-authority", context);
  const execution = await context.edges.invokes("executes-resolved-resolves-workspace-registry-request", authority);
  return context.edges.projects("projects-resolves-workspace-registry-request-receipt", execution);
}
