// @generated by scripts/project-linear-capability-bodies.mjs

export const registersPersistsWorkspaceRegistrySnapshotAuthority = Object.freeze({
  capabilityId: "persists-workspace-registry-snapshot",
  authorityRoot: "capabilities/persists-workspace-registry-snapshot",
  status: "drafted",
  executionModelId: "executes-persists-workspace-registry-snapshot",
  implementationDisposition: "semantic-authority-not-yet-implemented",
});
