// @generated by scripts/project-linear-capability-bodies.mjs
// Source: capabilities/observes-workspace-json-document/3-semantic-execution-models/observes-workspace-json-document.execution.sej.v1.json
import type { ObservesWorkspaceJsonDocumentContext } from "../types/observes-workspace-json-document-context.type.js";

export async function observesWorkspaceJsonDocument(
  context: ObservesWorkspaceJsonDocumentContext,
): Promise<unknown> {
  const authority = await context.edges.invokes("resolves-observes-workspace-json-document-authority", context);
  const execution = await context.edges.invokes("executes-resolved-observes-workspace-json-document", authority);
  return context.edges.projects("projects-observes-workspace-json-document-receipt", execution);
}
