// @generated by scripts/project-linear-capability-bodies.mjs

export const projectsCapabilityBody = Object.freeze({
  capabilityId: "projects-workspace-registry-snapshot",
  executionModelId: "executes-projects-workspace-registry-snapshot",
  bodyIdentity: "projects-workspace-registry-snapshot",
  source: "capabilities/projects-workspace-registry-snapshot/3-semantic-execution-models/projects-workspace-registry-snapshot.execution.sej.v1.json",
  status: "drafted",
});
