// @generated by scripts/project-linear-capability-bodies.mjs

export const projectsCapabilityTypes = Object.freeze({
  capabilityId: "projects-workspace-registry-snapshot",
  contextContract: "projects-workspace-registry-snapshot.input.v1",
  resultContract: "projects-workspace-registry-snapshot.receipt.v1",
  status: "drafted",
});
