// @generated by scripts/project-linear-capability-bodies.mjs

export const projectsCapabilityTypes = Object.freeze({
  capabilityId: "resolves-workspace-document-references",
  contextContract: "resolves-workspace-document-references.input.v1",
  resultContract: "resolves-workspace-document-references.receipt.v1",
  status: "drafted",
});
