// @generated by scripts/project-linear-capability-bodies.mjs

export const projectsCapabilityBody = Object.freeze({
  capabilityId: "resolves-workspace-document-references",
  executionModelId: "executes-resolves-workspace-document-references",
  bodyIdentity: "resolves-workspace-document-references",
  source: "capabilities/resolves-workspace-document-references/3-semantic-execution-models/resolves-workspace-document-references.execution.sej.v1.json",
  status: "drafted",
});
