// @generated by scripts/project-linear-capability-bodies.mjs

export const registersClassifiesWorkspaceJsonDocumentAuthority = Object.freeze({
  capabilityId: "classifies-workspace-json-document",
  authorityRoot: "capabilities/classifies-workspace-json-document",
  status: "drafted",
  executionModelId: "executes-classifies-workspace-json-document",
  implementationDisposition: "semantic-authority-not-yet-implemented",
});
