// @generated by scripts/project-linear-capability-bodies.mjs

export const projectsCapabilityBody = Object.freeze({
  capabilityId: "classifies-workspace-json-document",
  executionModelId: "executes-classifies-workspace-json-document",
  bodyIdentity: "classifies-workspace-json-document",
  source: "capabilities/classifies-workspace-json-document/3-semantic-execution-models/classifies-workspace-json-document.execution.sej.v1.json",
  status: "drafted",
});
