// @generated by scripts/project-linear-capability-bodies.mjs

export const projectsCapabilityTypes = Object.freeze({
  capabilityId: "classifies-workspace-json-document",
  contextContract: "classifies-workspace-json-document.input.v1",
  resultContract: "classifies-workspace-json-document.receipt.v1",
  status: "drafted",
});
