// @generated by scripts/project-linear-capability-bodies.mjs

export const projectsCapabilityBody = Object.freeze({
  capabilityId: "builds-workspace-registry",
  executionModelId: "executes-builds-workspace-registry",
  bodyIdentity: "builds-workspace-registry",
  source: "capabilities/builds-workspace-registry/3-semantic-execution-models/builds-workspace-registry.execution.sej.v1.json",
  status: "drafted",
});
