// @generated by scripts/project-linear-capability-bodies.mjs

export const projectsCapabilityTypes = Object.freeze({
  capabilityId: "builds-workspace-registry",
  contextContract: "builds-workspace-registry.input.v1",
  resultContract: "builds-workspace-registry.receipt.v1",
  status: "drafted",
});
