// @generated by scripts/project-linear-capability-bodies.mjs

export const registersResolvesWorkspaceRegistryRequestAuthority = Object.freeze({
  capabilityId: "resolves-workspace-registry-request",
  authorityRoot: "capabilities/resolves-workspace-registry-request",
  status: "drafted",
  executionModelId: "executes-resolves-workspace-registry-request",
  implementationDisposition: "semantic-authority-not-yet-implemented",
});
