// @generated by scripts/project-linear-capability-bodies.mjs

export const projectsCapabilityTypes = Object.freeze({
  capabilityId: "summarizes-workspace-registry",
  contextContract: "summarizes-workspace-registry.input.v1",
  resultContract: "summarizes-workspace-registry.receipt.v1",
  status: "drafted",
});
