// @generated by scripts/project-linear-capability-bodies.mjs

export const projectsCapabilityBody = Object.freeze({
  capabilityId: "summarizes-workspace-registry",
  executionModelId: "executes-summarizes-workspace-registry",
  bodyIdentity: "summarizes-workspace-registry",
  source: "capabilities/summarizes-workspace-registry/3-semantic-execution-models/summarizes-workspace-registry.execution.sej.v1.json",
  status: "drafted",
});
